Repository GoliasVictor/jogo., pull requests merged in 2024-06, with the labels that each got.

#1 GameSystem class added
  src/Jogo/IAudio.cs
  src/Jogo/Program.cs
Labels: engine

#14 Adicionar Game Design Document
  GameDesignDocument.md
  res/door.png
  res/element-items.png
  res/element-relation.png
  res/enemies-sheet.png
  res/fire-tile.png
  res/grass-tile.png
  res/key.png
  res/mock-final.png
  res/player-neutral.png
  res/player-sprites.png
  res/wall.png
  res/water-tile.png
Labels: board

#26 Implementação das Entidades e das Mecânicas
  src/Jogo/Entities/Block/Box.cs
  src/Jogo/Entities/Block/FireEntity.cs
  src/Jogo/Entities/Block/WaterEntity.cs
  src/Jogo/Entities/Element.cs
  src/Jogo/Entities/Floor/DoorEntity.cs
  src/Jogo/Entities/Floor/WallEntity.cs
  src/Jogo/Entities/IElemental.cs
  src/Jogo/Entities/IEntity.cs
  src/Jogo/Entities/IItemEntity.cs
  src/Jogo/Entities/Items/ElementChangerEntity.cs
  src/Jogo/Entities/Items/Key.cs
  src/Jogo/Entities/Layer.cs
  src/Jogo/Entities/characters/Enemy.cs
  src/Jogo/Entities/characters/Player.cs
  src/Jogo/GridVec2.cs
  src/Jogo/Map.cs
  src/Jogo/Models/BlockEntity.cs
  src/Jogo/Models/EmptyEntity.cs
  src/Jogo/Models/PlayerEntity.cs
  src/Jogo/Program.cs
  src/Jogo/Systems/CollisionSystem.cs
  src/Jogo/Systems/ElementalConflitSolver.cs
  src/Jogo/Systems/IAudio.cs
  src/Jogo/Systems/IScene.cs
  src/Jogo/Systems/ISystem.cs
  src/Jogo/Systems/ItemCollectionSystem.cs
  src/Jogo/Systems/LevelScene.cs
  src/Jogo/Systems/PlayerMovementSystem.cs
  src/Jogo/Systems/TickUpdateSystem.cs
Labels: engine, board

#25 Adicionar Sprite Importer
  src/Jogo/Assets/sprite-atlas.png
  src/Jogo/Program.cs
  src/Jogo/Sprite.cs
  src/Jogo/SpriteAtlas.cs
Labels: engine

#29 Atualizar visual das fases
  src/Jogo/.vscode/launch.json
  src/Jogo/.vscode/tasks.json
  src/Jogo/Assets/sprite-atlas.png
  src/Jogo/Entities/Block/Box.cs
  src/Jogo/Entities/Block/FireEntity.cs
  src/Jogo/Entities/Block/WaterEntity.cs
  src/Jogo/Entities/Floor/DoorEntity.cs
  src/Jogo/Entities/Floor/WallEntity.cs
  src/Jogo/Entities/Items/ElementChangerEntity.cs
  src/Jogo/Entities/Items/Key.cs
  src/Jogo/Entities/characters/Enemy.cs
  src/Jogo/Entities/characters/Player.cs
  src/Jogo/Program.cs
  src/Jogo/Systems/IScene.cs
  src/Jogo/Systems/LevelScene.cs
Labels: engine

#32 Add LevelBuilder and LevelLoader
  src/Jogo/Entities/Block/Goal.cs
  src/Jogo/Entities/characters/Enemy.cs
  src/Jogo/Jogo.csproj
  src/Jogo/LevelLoader.cs
  src/Jogo/Levels/custom-levels.yaml
  src/Jogo/Program.cs
  src/Jogo/Systems/LevelBuilderScene.cs
  src/Jogo/Systems/LevelScene.cs
Labels: engine

#36 Sound effects
  src/Jogo/Assets/Audio/audio-credits.txt
  src/Jogo/Assets/Audio/sfx-death.wav
  src/Jogo/Assets/Audio/sfx-key.wav
  src/Jogo/Entities/Block/Box.cs
  src/Jogo/Entities/Block/Goal.cs
  src/Jogo/Entities/Floor/DoorEntity.cs
  src/Jogo/Entities/Floor/WallEntity.cs
  src/Jogo/Entities/Items/ElementChangerEntity.cs
  src/Jogo/Entities/Items/Key.cs
  src/Jogo/Entities/characters/Player.cs
  src/Jogo/Jogo.csproj
  src/Jogo/Systems/Audio.cs
  src/Jogo/Systems/IAudio.cs
Labels: audio
